spring:
  liquibase:
    enabled: false
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: postgres
spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.suffix: .ftl