app:
  emailer: true
  lang: en
  county: US
spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: "[Login]"
    password: "[Password]"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  liquibase:
    enabled: false
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: postgres
  freemarker:
    template-loader-path: classpath:/templates
    :suffix: .ftl

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true