spring:
  liquibase:
    enabled: false
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: postgres
  freemarker:
    template-loader-path: classpath:/templates
    :suffix: .ftl

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
